import {
	Apple,
	Pizza,
	Hamburger,
	Utensils,
	Handbag,
	Luggage,
	Shirt,
	Gift,
	Gem,
	Laptop,
	Router,
	Phone,
	Signal,
	AudioLines,
	Pill,
	Smile,
	Cannabis,
	House,
	Zap,
	CarTaxiFront,
	Bus,
	Car,
	Beer,
	HatGlasses,
	Bone,
	Dumbbell,
	Plane,
	BanknoteX,
	Music,
	RadioTower,
	Popcorn,
	Heart,
	HandMetal,
	Guitar,
	Scissors,
	Venus,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

export const categoryIconMap: Record<string, LucideIcon> = {
	Apple: Apple,
	Pizza: Pizza,
	Hamburger: Hamburger,
	Utensils: Utensils,
	Handbag: Handbag,
	Luggage: Luggage,
	Shirt: Shirt,
	Gift: Gift,
	Gem: Gem,
	Laptop: Laptop,
	Router: Router,
	Phone: Phone,
	Signal: Signal,
	AudioLines: AudioLines,
	Pill: Pill,
	Smile: Smile,
	Cannabis: Cannabis,
	House: House,
	Zap: Zap,
	CarTaxiFront: CarTaxiFront,
	Bus: Bus,
	Car: Car,
	Beer: Beer,
	HatGlasses: HatGlasses,
	Bone: Bone,
	Dumbbell: Dumbbell,
	Plane: Plane,
	BanknoteX: BanknoteX,
	Music: Music,
	RadioTower: RadioTower,
	Popcorn: Popcorn,
	Heart: Heart,
	HandMetal: HandMetal,
	Guitar: Guitar,
	Scissors: Scissors,
	Venus: Venus,
}

export const categoryIconOptions = Object.entries(categoryIconMap).map(([key, Icon]) => ({
	key,
	label: key,
	Icon,
}))
